art/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login, LogoutView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('art_app.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url("^logout/$", LogoutView.as_view(),{"next_page":"/"}),
 
   
]

art_app/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns =[
    url(r'^$',views.index,name = 'index'),
    url(r'^new/upload$', views.upload_art, name='upload'),
    url(r'^new/profile$', views.add_profile, name='edit'),
    url(r'^myprofile$',views.my_profile,name ='myprofile'),
    url(r'^oneart/(\d+)$', views.one_art, name='oneart'),
    url(r'^search/$', views.search_art, name='search'),
    url(r'^comment/(\d+)/$', views.add_comment, name='comment'),
    url(r'^view_comment/(\d+)/$', views.comment, name='view'),
    url(r'^category/(?P<category>\w+)',views.image_category,name ='category')
    
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

art_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator



class Category(models.Model):
    name = models.CharField(max_length=60, default="")
   

    @classmethod
    def get_categories(cls):
        categories = Category.objects.all()
        return categories
    def __str__(self):
        return self.name

    @classmethod
    def update_categories(cls, id, value):
        cls.objects.filter(id=id).update(art=value)
    def save_category(self):
        self.save()
    def delete_category(self):
        self.delete()

class Art(models.Model):
    title = models.CharField(max_length=155)
    art_image = models.ImageField(upload_to='landing_images/', null=True)
    description = models.TextField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)
    

    

    @classmethod
    def filter_by_category(cls, category):
        image_category = Art.objects.filter(category__name=category).all()
        return image_category

    @classmethod
    def get_all_arts(cls):
        all_arts = cls.objects.all()
        return all_arts

    def save_arts(self):
        self.save()


    def delete_arts(self):
        self.delete()


    @classmethod
    def search_by_title(cls,search_term):
        certain_user = cls.objects.filter(title__icontains = search_term)
        return certain_user


    def __str__(self):
        return self.title


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_photo/', null=True)
    bio = models.CharField(max_length=255)
    
    contact = models.TextField(max_length=255)
    arts = models.ForeignKey(Art, on_delete=models.CASCADE, null=True)

    @classmethod
    def get_profile(cls):
        all_profiles = cls.objects.all()
        return all_profiles

    def save_profles(self):
        self.save()


    def delete_profiles(self):
        self.delete()


    def __str__(self):
        return str(self.user)


class Comments(models.Model):
    comment = models.CharField(max_length=250)
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    posted_by = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    commented_art = models.ForeignKey(Art, on_delete=models.CASCADE, null=True)

    def save_comments(self):
        self.save()

    def delete_comments(self):
        self.delete()

    def __str__(self):
        return self.posted_by





   

art_app/forms.py
from django import forms
from .models import Profile,Art,Comments
from django.forms import ModelForm,Textarea,IntegerField

class NewArtForm(forms.ModelForm):
    class Meta:
        model = Art
        exclude = ['user','arts']

class NewProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user','arts']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        exclude = ['posted_by', 'commented_art','user']
        

art_app/views.py
from django.shortcuts import render,redirect
from django.http  import HttpResponse,Http404,HttpResponseRedirect
import datetime as dt
from .models import Profile,Art,Comments,Category
from django.contrib.auth.decorators import login_required
from .forms import NewArtForm,NewProfileForm,CommentForm

# Create your views here.

def index(request):
    ones_art = Art.objects.all()
    all_arts = Art.get_all_arts()
    categories = Category.get_categories()
    print(categories)
    return render(request, 'index.html', {"all_arts": all_arts, "ones_art":ones_art, "categories": categories})
    
@login_required(login_url='/accounts/login/')
def image_category(request, category):
    images = Art.filter_by_category(category)
    print(images)
    return render(request, 'category.html', {'category_images': images})

@login_required(login_url='/accounts/login/')
def upload_art(request):
    current_user = request.user
    if request.method == 'POST':
        form = NewArtForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.user = current_user
            image.save()
        return redirect('index')
    else:
        form = NewArtForm()
    return render(request, 'upload_art.html', {"form": form})

@login_required(login_url='/accounts/login/')
def one_art(request,id):
    ones_art = Art.objects.filter(id = id)
    return render(request,'art.html',{"ones_art":ones_art,}) 

@login_required(login_url='accounts/login/')
def add_profile(request):
    current_user = request.user
    profile = Profile.objects.filter(id = current_user.id)
    if request.method == 'POST':
        form = NewProfileForm(request.POST, request.FILES)
        if form.is_valid():
            caption = form.save(commit=False)
            caption.user = current_user
            caption.save()
            return redirect('myprofile')
    else:
        form = NewProfileForm()
    return render(request, 'edit_profile.html', {"form":form})  

@login_required(login_url='accounts/login/')
def my_profile(request):
    current_user = request.user
    my_arts = Art.objects.filter(user = current_user)
    my_profile = Profile.objects.filter(user = current_user).first
    return render(request, 'profiles.html', {"my_arts": my_arts, "my_profile":my_profile})

def search_art(request):
    if 'art_name' in request.GET and request.GET["art_name"]:
        search_term = request.GET.get("art_name")
        searched_art = Art.search_by_title(search_term)
        message = f"{search_term}"
        return render(request, "search.html",{"message":message,"art": searched_art})
    else:
        message = "You haven't searched for any term"
        return render(request, 'search.html',{"message":message})

@login_required(login_url='/accounts/login/')
def add_comment(request, art_id):
    current_user = request.user
    art_item = Art.objects.filter(id = art_id).first()
    profiless = Profile.objects.filter(user = current_user.id).first()
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.posted_by = profiless
            comment.commented_art = art_item
            comment.save()
            return redirect('oneart',art_id)
    else:
        form = CommentForm()
    return render(request, 'comment_form.html', {"form": form, "art_id": art_id})


def comment(request, id):
    mycomments = Comments.objects.filter(commented_art = id).all()
    return render(request, 'comments.html', {"mycomments":mycomments})

art_app/templates/art.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<div class="container" style="margin-top:3%;font-family: 'Lancelot', cursive;">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card mb-4 shadow-sm">
                {% for image in ones_art %}
                <span style="font-weight: bold;font-size: 20px; margin:3%">{{image.title}}</span>
                <a href="{{image.link}}">
                    <img src="{{image.art_image.url}}" width="100%" class="img-responsive"></a>
                <div class="card-body">
                    <span><small
                        style="text-transform:capitalize;font-family: 'Rancho', cursive;">posted by__{{image.user}}</small>
                </span>
                
                    <span style="float:right">
                        <a href="{%url 'comment' image.id%}" class="btn btn-default btn-sm">Add Comment</a></span>

                    <p style="font-size: 15px;">{{image.description}}</p>
                    <p style="font-family: 'Old Standard TT', serif;font-size: 15px;">category:{{image.category}}</p>
                    <p style="font-weight: bold;font-size: 15px;color: rgba(0, 0, 0, 0.459);margin-top: 3px;">
                        View all comments...</p>
                    {% for reviews in image.comments_set.all %}
                    <span>
                        <p style="font-size: 15px;margin-top: -0.3cm;">
                            <span style="font-weight: bold; font-size: 15px">{{reviews.posted_by.user | lower }}</span>
                            {{reviews.comment}}
                        </p>
                    </span>
                    {% endfor %}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-md-2"></div>
    </div>
</div>

{% endblock %}

art_app/templates/base.html
{% load bootstrap4 %}
{% load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
  {% if title %}
  <title>Arts - {{title}}</title>
  {% else %}
    <title> Arts </title>
  {% endif %}
  {% block styles %}
    {% bootstrap_css %}
    <link href="https://fonts.googleapis.com/css2?family=Rancho&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Old+Standard+TT&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lancelot&display=swap" rel="stylesheet">

     <script src="https://kit.fontawesome.com/83d474e45f.js" crossorigin="anonymous"></script>
  {% endblock %}
</head>
<body>
    {% include "navbar.html" %}
    {% block content %}
     {%endblock%}
    {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
       
     {% bootstrap_javascript %}
    {% endblock %}
</body>
</html>
</html>

art_app/templates/category.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="font-family: 'Libre Caslon Display', serif;">
   <h2>Art</h2>
    <hr>
    {% if category_images %}
     
    <div class="card-columns">
        {% for art in category_images %}

        <div class="card" data-toggle="modal" data-target="#{{art.id}}">
            <img src="{{art.art_image.url}}" alt="{{art.name}}" width="100%" height="300px" class="img-responsive">
            <p>{{art.description}}</p>
                      
                        <p>{{art.category}}</p>
        </div>
        <div class="modal fade" id="{{art.id}}" tabindex="-1" role="dialog" aria-labelledbly="exampleModalCenterTitle"
            aria-hidden="true">

            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content modalcard">
                    <div class="modal-header">
                        <h5 class="modal-title d-block mx-auto" id="exampleModalLongTitle">{{art.name}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    

                    
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

art_app/templates/comment_form.html
{% load bootstrap4 %} 
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Comment</title>
  {{form.media}}
  {% block styles %} 
  {% bootstrap_css %}
 
  {% endblock %}
</head>
<body>
<div class="container-fluid"
  style="background-image:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),url('https://di2ponv0v5otw.cloudfront.net/posts/2020/01/28/5e30a341abe1ce823bb2127e/m_5e30a34b8557af49b64d2301.jpg') ;background-repeat:no-repeat;background-size:cover;height:100vh;background-position: center;color:white;font-family: 'Lancelot', cursive;">
<div class="row">
<div class="col-md-4"></div>
    <div class="col-md-4">
<h1 class="text-center" style="margin-top: 3%;">Add a comment</h1>
  <form  action="{%url 'comment' art_id%}" method="post" enctype="multipart/form-data" style="margin-right:15%;margin-left:15%;">
    {%csrf_token%}
    {% bootstrap_form form%}
    <input type="submit" class="btn btn-outline-info btn-lg" value="Post">
  </form>
   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %} 
  {% endblock %}
</div>
</div>
</div>
</div>
</body>
</html>

art_app/templates/comments.html
{%extends 'base.html'%}
{% load static %}
{% block content %}
{{block.super}}

<div class="container">
    <div class="row" style="margin-top: 3%">
        <div class="col-md-12">
                <h2 style="margin-top: 3%; margin-bottom:3%">All comments</h2>
        {% for acomment in mycomments %}
        <p>{{acomment.comment}}</p>
        
        {% endfor %}
        </div>
    </div>  
</div>
{% endblock %}

art_app/templates/edit_profile.html
{% load bootstrap4 %} 
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Profile</title>
  {{form.media}}
  {% block styles %} 
  {% bootstrap_css %}

  {% endblock %}
</head>
<body style="background-color: gainsboro;font-family: 'Lancelot', cursive;">
<div class="container-fluid"
  style="background-image:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),url('https://di2ponv0v5otw.cloudfront.net/posts/2020/01/28/5e30a341abe1ce823bb2127e/m_5e30a34b8557af49b64d2301.jpg') ;background-repeat:no-repeat;background-size:cover;height:100vh;background-position: center;color:white;font-family: 'Lancelot', cursive;">

  <div class="row">
  
<div class="col-md-4"></div>
    <div class="col-md-4">
<h1 class="text-center" style="margin-top: 3%;">Add your profile</h1>
  <form  action="{%url 'edit' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {% bootstrap_form form%}
    <input type="submit" class="btn btn-outline-info btn-lg" value="Post">
  </form>
   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %} {% endblock %}
</div>
</div>
</div>
</body>
</html>

art_app/templates/index.html
{%extends 'base.html'%}
{% load static %}
{% block content %}
{{block.super}}


<div class="container" style="padding-top: 3%;">
    <h1 class="text-center" style="margin-top:4%;font-family: 'Lancelot', cursive;">ARTS of the country of thousand hills</h1>
<p class="text-center" style="font-family: 'Lancelot', cursive;">Art Rwanda is an application that helps you to know more about <br> Rwandan culture through their art(Ubuhanzi). <br>
    <button class="btn btn-info btn-sm" style="margin-bottom:4%;"> <a class="nav-link" href="{%url 'upload'%}" style="color:white;">Add an Art</a></button>
</p>
   
    <div class="row">
        {% for art in all_arts %}
        <div class="col-md-4">
            <div class="card mb-4 shadow-lg">
                <a href="{% url 'oneart' art.id %}">
                    <img src="{{art.art_image.url}}" width="100%" height="300px" class="img-responsive">
                </a>
                <div class="card-body">

                    <span style="font-family: 'Rancho', cursive;">{{art.title}} </span>
                    
                    <span style="font-family: 'Rancho', cursive; margin-left:9px;"><small>{{art.date|date:"F d,Y"}}</small>
                        <button class="btn btn-outline-info btn-sm" style="float:right;"><a
                            href="{% url 'oneart' art.id %}" style="font-family: 'Rancho', cursive;color:black;">view comments </a></button>
                    </span><br>

                    <div class="foot">
                        <small style="font-family: 'Old Standard TT', serif;">{{art.description}}</small><br><br>

                       
                    </div>

                </div>


            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

{% block scripts %}
{{block.super}}
<script type="text/javascript" src="{%static 'js/newsletter.js'%}">
</script>
{% endblock %}

art_app/templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/83d474e45f.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Trocchi&display=swap" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-white bg-black static-top" style="background-color:black;font-family: 'Trocchi', serif;">
        <div class="container">

            <div class="home">
                <a class="navbar-brand" href="{%url 'index'%}">

                    <span style="color: white;font-size:15px;">Art- <img src="https://img.freepik.com/free-vector/flag-rwanda-background-template_19426-608.jpg?size=626&ext=jpg" alt="" width="50px" height="50px"> </span>

                </a>
            </div>

            <div class="search" style="margin-right:10%;font-size:15px;">
        <form action="{% url 'search' %}" class="form-inline my-2 my-lg-0">
          <input type="text" class="input-sm form-control" name="art_name" placeholder="Search"
            style="border: 0px; border-bottom: 2px solid white; outline: none; margin-left: 40%;background-color:black;color:white;font-size:18px;">

        </form>
      </div>

      
<div class="category">
      <span id="categories">
        {% for category in categories %}
        <a  href="/category/{{category.name}}" style="color: white;font-size:15px; text-transform:capitalize;">{{category.name}} &nbsp; &nbsp;</a>
        {% endfor %}
      </span>
    </div>


            {% if user.is_authenticated %}
            <ul class="nav justify-content-end">

                 <a class="nav-link" href="{%url 'myprofile'%}"
                    style="font-family: 'Noto Serif JP', serif;color:white;text-transform:capitalize;font-size:15px;"><i
                        class="fas fa-user fa-sm"></i>{{user.username}}</a>

                <div class="dropdown" style="margin-top: 4%">
                    <a class="down" data-toggle="dropdown" style="font-family: 'Noto Serif JP', serif;color:black;"><i
                            class="fa fa-sun-o" style="font-size: 15px;color: white;">Account</i></a>
                    <div class="dropdown-menu">
                        
                        <a class="nav-link" href="/accounts/register/" style="color:black">Register</a>
                      
                        <a class="dropdown-item" href="/accounts/password/change"
                            style="font-family: 'Noto Serif JP', serif;color:black;">Change Password</a>
                        <a class="dropdown-item" href="/logout"
                            style="font-family: 'Noto Serif JP', serif;color:black;">Logout</a>
                    </div>
                </div>
                {% else %}
                
                    <a class="nav-link" href="/accounts/login"
                        style="font-family: 'Noto Serif JP', serif;color:white;">Login</a>
               
            </ul>
            {% endif %}
        </div>

        </div>
        </div>
    </nav>

</body>

</html>

art_app/templates/profiles.html
{%extends 'base.html'%}
{% block content %}
{{block.super}}

<div class="container" style="margin-top:8%;font-family: 'Lancelot', cursive;">

    <div class="row" >
        <div class="col-md-4">
            <div class="profile" style="margin-top: -7%">
                <img src="{{my_profile.profile_picture.url}}" class="rounded-circle account-img d-block mx-auto"
                    height="200px" width="200px">
            </div>

        </div>
        <div class="col-md-8">
            
            <div class="imagecaption" style="margin-left: 15%">
                <h5 style="text-transform: capitalize;">Name: {{my_profile.user}}</h5>
                <h5>Bio: {{my_profile.bio}}</h5>
                <h5>contact: {{my_profile.contact}}</h5>
                <a class="btn btn-outline-info" href="{%url 'edit'%}" style="color: black;">Create Profile</a>
            </div>
        </div>
    </div>
    <hr>
</div>
<div class="container">

 <div class="row">
        {% for user in my_arts %}
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <img src="{{user.art_image.url}}" width="100%" height="200" class="img-responsive" alt="Image">
                <div class="card-body">
                    <p style="font-weight: bold;font-family: 'Times New Roman', Times, serif;margin-top: -0.4cm;margin-bottom: -1cm;">{{user.category}}</p>
                </div>
            </div>
        </div>
        
        {% endfor %}
    </div>
  
</div>
    {% endblock %}

art_app/templates/search.html
{%extends 'base.html'%}
{% block content %}
<div class="container" style="font-family: 'Lancelot', cursive;">
  <div class="row" style="margin-top:4%">
    {% if art%}
    <h5 class='text-center'>You have {{ art|length }} project with name {{message }}</h2>
        {% else %}
        <h5 class="text-center"> You have 0 project with name search <strong>{{message}}</strong></h5>
        <a class="d-block mx-auto" href="/">
            <button class="btn btn-sm btn-outline-info d-block mx-auto">Back Home</button>
        </a>
        {% endif %}
        <hr style="margin-left:5%;margin-right:12%">
    {% if art %}
    {% for artname in art %}
    <div class="col-md-4">
      <h3>{{art.title}}</h3>
      <img src="{{artname.art_image.url}}" width="400" height="300" class="img-responsive" alt="Image">
      <p style="margin-top: 5%">{{artname.description}}</p>
    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}

art_app/templates/upload_art.html
{% load bootstrap4 %} 
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Upload</title>
  {{form.media}}
  {% block styles %} 
  {% bootstrap_css %}
  <link href="https://fonts.googleapis.com/css2?family=Lancelot&display=swap" rel="stylesheet">
  {% endblock %}
</head>
<body style="background-color:gainsboro">
<div class="container-fluid" style="background-image:linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),url('https://pbs.twimg.com/media/Eb9ri4FXsAEDWDK.jpg') ;background-repeat:no-repeat;background-size:cover;height:110vh;color:white;font-family: 'Lancelot', cursive;color:black;padding-top:30px;background-position: center;color:white;">
<div class="row">
<div class="col-md-4"></div>
    <div class="col-md-4">
  <h1 class="text-center" style="margin-top: 3%;">Upload your art</h1>
  <form  action="{%url 'upload' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {% bootstrap_form form%}
    <input type="submit" class="btn btn-outline-info btn-lg" value="Post">
  </form>
   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %} {% endblock %}
</div>
</div>
</div>
</div>
</body>
</html>